server:
  port: 7019
spring:
  main:
    allow-circular-references: true
    allowBeanDefinitionOverriding: true
  datasource:
    primary:
      jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      username: root
      password: Root123456
    secondary:
      jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      username: root
      password: Root123456
  #  sql:
#    init:
#      schema-locations: classpath*:db/schema.sql
#      data-locations: classpath*:db/data.sql
#  security:
#    user:
#      name: admin
#      password: admin
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect_resolvers: top.yxlgx.wink.config.orm.jpa.CustomStandardDialectResolver
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true

  h2:
    console:
      enabled: true
      settings:
        web-admin-password: 123456
        web-allow-others: true
logging:
  level:
    org.hibernate.tool: debug
mybatis:
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: top.yxlgx.wink.entity

security:
  adminUser: admin
  adminPassword: admin
  jwsKey: "3F4428472B4B6250655368566D5971337336763979244226452948404D635166"

project:
  security:
    header: "Authorization"
    tokenPrefix: "Bearer "
    secretKey: "3F4428472B4B6250655368566D5971337336763979244226452948404D635166"
