server:
  port: 7019
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks
  main:
    allow-circular-references: true
    allowBeanDefinitionOverriding: true
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3307/demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: 123456
  #  sql:
#    init:
#      schema-locations: classpath*:db/schema.sql
#      data-locations: classpath*:db/data.sql
#  security:
#    user:
#      name: admin
#      password: admin
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      password: 12345678
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-admin-password: 123456
#        web-allow-others: true
logging:
  level:
    org.hibernate.tool: debug

security:
  adminUser: admin
  adminPassword: admin
  jwsKey: "3F4428472B4B6250655368566D5971337336763979244226452948404D635166"

project:
  security:
    header: "Authorization"
    tokenPrefix: "Bearer "
    secretKey: "3F4428472B4B6250655368566D5971337336763979244226452948404D635166"
