server:
  port: 7019
spring:
  application:
    name: wink
  main:
    allow-circular-references: true
    allowBeanDefinitionOverriding: true
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3307/demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #  sql:
#    init:
#      schema-locations: classpath*:db/schema.sql
#      data-locations: classpath*:db/data.sql
#  security:
#    user:
#      name: admin
#      password: admin
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          fetch_size: 500
        max_fetch_depth: 3
        default_batch_fetch_size: 500
        hbm2ddl:
          default_constraint_mode: NO_CONSTRAINT
        dialect_resolvers: top.yxlgx.wink.common.jpa.handler.EnhanceDialectResolver
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-admin-password: 123456
#        web-allow-others: true
logging:
  level:
    org.hibernate.tool: debug

sa-token:
  # SSO-相关配置
  sso:
    # SSO-Server端 统一认证地址
    auth-url: http://127.0.0.1:9000/sso/auth

  # 配置Sa-Token单独使用的Redis连接 （此处需要和SSO-Server端连接同一个Redis）
  alone-redis:
    # Redis数据库索引 (默认为0)
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout: 10s

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.yxlgx.wink.admin
  enable-javadoc: true
  enable-native-support: true
  model-converters:
    pageable-converter:
      enabled: true
  components:
    # 鉴权方式配置
    security-schemes:
      apiKey:
        type: APIKEY
        in: HEADER
        name: ${sa-token.token-name}
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn