server:
  port: 7019
spring:
  main:
    allow-circular-references: true
    allowBeanDefinitionOverriding: true
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3307/demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #  sql:
#    init:
#      schema-locations: classpath*:db/schema.sql
#      data-locations: classpath*:db/data.sql
#  security:
#    user:
#      name: admin
#      password: admin
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          fetch_size: 500
        max_fetch_depth: 3
        default_batch_fetch_size: 500
        hbm2ddl:
          default_constraint_mode: NO_CONSTRAINT
        dialect_resolvers: top.yxlgx.wink.common.jpa.handler.MyStandardDialectResolver
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: 127.0.0.1
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-admin-password: 123456
#        web-allow-others: true
logging:
  level:
    org.hibernate.tool: debug

sa-token:
  sso:
    # 打开模式三（使用Http请求校验ticket）
    is-http: true
    # SSO-Server端 统一认证地址 
    auth-url: http://127.0.0.1:9000/sso/auth
    # SSO-Server端 ticket校验地址 
    check-ticket-url: http://127.0.0.1:9000/sso/checkTicket
    # 单点注销地址 
    slo-url: http://127.0.0.1:9000/sso/signout
    # SSO-Server端 查询数据地址 
    get-data-url: http://127.0.0.1:9000/sso/getData
    is-slo: true
  sign:
    # API 接口调用秘钥
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
    # ---- 除了以上配置项，你还需要为 Sa-Token 配置http请求处理器（文档有步骤说明）

forest:
  # 关闭 forest 请求日志打印
  log-enabled: false

